name: Build Chess App APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # --- THIS IS THE FIX ---
    # We don't use the broken 'gradlew' script.
    # Instead, we install Gradle directly onto the build machine.
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4' # Matches your properties file

    # The 'chmod +x' step is now gone.

    # We now use 'gradle' instead of './gradlew'
    - name: Build debug APK
      run: gradle assembleDebug
    # --- END OF FIX ---

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
